Starting server in PID 5204.
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/bin/pserve", line 9, in <module>
    load_entry_point('pyramid==1.3.2', 'console_scripts', 'pserve')()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/pyramid/scripts/pserve.py", line 47, in main
    return command.run()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/pyramid/scripts/pserve.py", line 311, in run
    serve()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/pyramid/scripts/pserve.py", line 301, in serve
    server(app)
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 189, in server_wrapper
    **context.local_conf)
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/paste/deploy/util.py", line 56, in fix_call
    val = callable(*args, **kw)
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/__init__.py", line 21, in serve_paste
    serve(app, **kw)
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/__init__.py", line 11, in serve
    server = _server(app, **kw)
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/server.py", line 57, in __init__
    self.bind((self.adj.host, self.adj.port))
  File "/usr/lib64/python2.6/asyncore.py", line 333, in bind
    return self.socket.bind(addr)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use
Removing PID file pyramid.pid
Starting server in PID 5425.
serving on http://0.0.0.0:6541
Starting server in PID 23985.
serving on http://0.0.0.0:6540
2012-12-19 19:11:39,720 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:11:39,723 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:11:39,950 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:11:39,953 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:11:42,664 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:11:42,668 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:11:58,700 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:11:58,797 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:11:58,837 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:11:58,842 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:12:08,857 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:12:08,860 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:12:13,950 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:12:13,954 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:12:26,447 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:12:26,451 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:12:30,753 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:12:30,756 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:12:48,880 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:12:48,884 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:12:54,693 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:12:54,697 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:12:54,751 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:12:54,757 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:12:54,784 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:12:54,787 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:13:05,396 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:13:05,401 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:13:06,831 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:13:06,835 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:13:07,684 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:13:07,688 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:13:12,858 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:13:12,862 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:13:15,268 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:13:15,272 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:13:55,376 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:13:55,381 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:13:56,737 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:13:56,743 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:14:15,581 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:14:15,584 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:14:28,684 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:14:28,688 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:14:28,708 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:14:28,712 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
2012-12-19 19:14:28,731 WARNI [waitress][MainThread] unhandled connect event
2012-12-19 19:14:28,734 ERROR [waitress][MainThread] Socket error
Traceback (most recent call last):
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 134, in handle_write
    flush()
  File "/app/web/virtualenv/pyramidenv/lib/python2.6/site-packages/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 249, in _flush_some
    num_sent = self.send(chunk)
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
error: [Errno 32] Broken pipe
